from frontend.dashboards.main_dashboard import main_dashboard_layout, setup_main_dashboard_callbacks
from frontend.dashboards.risk_analysis import risk_analysis_layout, setup_risk_analysis_callbacks
from frontend.dashboards.vehicle_analysis import vehicle_analysis_layout, setup_vehicle_analysis_callbacks